/**
 * Raw EsnekPos API types for payment-request (ödeme isteği) endpoints.
 *
 * Internal use only — never export from src/index.ts.
 */

/**
 * @endpoint POST /api/services/SendPaymentRequest
 * @req AMOUNT* INSTALLMENT*(0=no limit) PHONE_NUMBER* MAIL* TYPE*(1=SMS|2=Email|3=LinkOnly) LOCALE*(tr|en) IS_TOTAL_AMOUNT*(true=chargeAmount|false=netAmount) PRODUCT*
 * @res {STATUS RETURN_CODE RETURN_MESSAGE URL SendPaymentRequestId}
 * @note SendPaymentRequestId is PascalCase (not SCREAMING_SNAKE_CASE).
 */
// --- /api/services/SendPaymentRequest ---

export interface RawSendPaymentRequestResponse {
  RETURN_CODE: string;
  RETURN_MESSAGE: string;
  STATUS: string;
  /** The payment page URL generated by EsnekPos. */
  URL: string;
  /** Unique ID for this payment request — used to query its status later. */
  SendPaymentRequestId: string;
}

/**
 * @endpoint POST /api/services/SendPaymentRequestQuery
 * @req SEND_PAYMENT_REQUEST_ID*
 * @res {STATUS RETURN_CODE RETURN_MESSAGE PAYMENTS:[{REFNO PAYMENT_STATUS DATE PAYMENT_DATE AMOUNT ORDER_REF_NO INSTALLMENT COMMISSION COMMISSION_RATE SUCCESS_TRANSACTION_ID?}]}
 * @note ORDER_REF_NO (not ORDER_REF_NUMBER) — consistent with ProcessQuery.
 */
// --- /api/services/SendPaymentRequestQuery ---

export interface RawPaymentRequestPayment {
  REFNO: string;
  PAYMENT_STATUS: string;
  DATE: string;
  PAYMENT_DATE: string;
  AMOUNT: string;
  ORDER_REF_NO: string;
  INSTALLMENT: string;
  COMMISSION: number;
  COMMISSION_RATE: string;
  SUCCESS_TRANSACTION_ID: number | null;
}

export interface RawSendPaymentRequestQueryResponse {
  PAYMENTS: RawPaymentRequestPayment[];
  RETURN_CODE: string;
  RETURN_MESSAGE: string;
  STATUS: string;
}
